global:
  scrape_interval: 15s

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sample-app'
    static_configs:
      - targets: ['sample-app:8000']

  - job_name: 'ubuntu-host'
    static_configs:
      - targets: ['node-exporter:9100']
